name: ardour_ai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.1
  http: ^1.2.1
  flutter_secure_storage: ^4.2.1
  flutter_local_notifications: ^17.1.0


dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/happy/
    - assets/gifs/surprise/
    - assets/gifs/sad/
    - assets/gifs/missing/

  fonts:
    - family: antipasto
      fonts:
        - asset: assets/fonts/Zetafonts - AntipastoPro-DemiBold.otf

